### ISSUE TITLE
Are there any plans to enable parsing csv data on the memory buffer?

### ISSUE THREAD

**Issue by toge** [red0124/ssp#31]
Thank you for providing a great library.

I would like to use ssp to process not only csv files, but also responses from the server and data extracted from compressed files. 
Are there any plans to provide a method other than reading from a file?

**Comment by red0124** [comment]
I am glad the library is of some use to you.

If the buffer contains all of the csv data then I could add a constructor which accepts the buffer and the total data size instead of a file name, and read each line from the buffer instead of the file. This should not be hard to implement I think. I could add it.

If the buffer contains only the one current line, then you could use the ss::converter class to parse it. The usage is documented near the end of the README.

**Comment by red0124** [comment]
Buffer mode is available as of version 1.7.0.

**Comment by toge** [comment]
@red0124 
Thanks a lot!
